server:
  port: 7000

logging:
  level:
    me.lawrenceli: debug

spring:
  application:
    name:
      gateway-server
  redis:
    host: host.docker.internal
    port: 6379
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: 39.104.224.205:8848
        namespace: yh
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: path-route
          uri: lb://websocket-server
          predicates:
            - Path=/websocket/**
          filters:
            - StripPrefix=1

websocket:
  service:
    name: 'websocket-server'
  docker:
    network: 'compose-network'
    host: 'tcp://host.docker.internal:2375'
    image:
      name: 'websocket:1.0.0'
